### ISSUE TITLE
BlocProvider.of() called with a context that does not contain a Bloc of type EntryBloc.

### ISSUE THREAD

**Issue by duomoteng** [felangel/bloc#1131]
A button is on the appbar, I want to use bloc to prompt a dialog, however, it shows me the `BlocProvider.of() called with a context that does not contain a Bloc of type EntryBloc.`

My code is 

```dart
class NotebookEntryPageProvider extends StatelessWidget {
  @override
Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => NotebookEntryBloc()..add(FetchNotebook()),
        child: Scaffold(
        floatingActionButton: Center(
          child: FloatingActionButton(
            child: CupertinoTextField(),
            //todo: set on pressed
            onPressed: () {},
          ),
        ),
        body: CupertinoPageScaffold(
              navigationBar: CupertinoNavigationBar(
                middle: Text("Title"),
                trailing:
                GestureDetector(
                  onTap: () {
                    BlocProvider.of<NotebookEntryBloc>(context).add(AddNew());
                  },
                  child:Icon(CupertinoIcons.add)
                )
              ),
              child: EntryPage()),
        ),
      ),
    );
}

```

The error is 
```
The following assertion was thrown while handling a gesture:
        BlocProvider.of() called with a context that does not contain a Bloc of type NotebookEntryBloc.

        No ancestor could be found starting from the context that was passed to BlocProvider.of<NotebookEntryBloc>().

        This can happen if the context you used comes from a widget above the BlocProvider.

        The context used was: NotebookEntryPageProvider
        
When the exception was thrown, this was the stack: 
#0      BlocProvider.of (package:flutter_bloc/src/bloc_provider.dart:106:7)
#1      NotebookEntryPageProvider.build.<anonymous closure> (package:beluganote/pages/notebook_entry_page.dart:32:38)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#dc9a7
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(343.0, 46.5)
  finalLocalPosition: Offset(16.0, 20.5)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by masfranzhuo** [comment]
Try to put BlocPrivider in the Scaffold like this
```
Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => bookEntryBloc()..add(Fetchbook()),
        child: Scaffold(
        floatingActionButton: Center(
          child: FloatingActionButton(
            child: CupertinoTextField(),
            //todo: set on pressed
            onPressed: () {},
          ),
        ),
        body: CupertinoPageScaffold(
              navigationBar: CupertinoNavigationBar(
                middle: Text("Title"),
                trailing:
                GestureDetector(
                  onTap: () {
                    BlocProvider.of<EntryBloc>(context).add(AddNew());
                  },
                  child:Icon(CupertinoIcons.add)
                )
              ),
              child: EntryPage()),
        ),
      ),
    );
}
```
Does its help?

**Comment by duomoteng** [comment]
It still shows the same error

**Comment by masfranzhuo** [comment]
May I know what is `bookEntryBloc`, could you provide the full code

**Comment by duomoteng** [comment]
This is my full original code
```dart
class NotebookEntryPageProvider extends StatelessWidget {
  @override
Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => NotebookEntryBloc()..add(FetchNotebook()),
        child: Scaffold(
        floatingActionButton: Center(
          child: FloatingActionButton(
            child: CupertinoTextField(),
            //todo: set on pressed
            onPressed: () {},
          ),
        ),
        body: CupertinoPageScaffold(
              navigationBar: CupertinoNavigationBar(
                middle: Text("Title"),
                trailing:
                GestureDetector(
                  onTap: () {
                    BlocProvider.of<EntryBloc>(context).add(AddNew());
                  },
                  child:Icon(CupertinoIcons.add)
                )
              ),
              child: EntryPage()),
        ),
      ),
    );
}

```

```dart

class NotebookEntryBloc extends Bloc<NotebookEntryEvent, NotebookEntryState> {
  /// How many entries need to fetch from db once.
  final int _fetchNumber = 20;

  NotebookEntryBloc();

  @override
  get initialState {
    List<Notebook> _list = [];
    return NotebookUninitialized(notebooks: _list, hasReachedMax: false);
  }

  
  @override
  Stream<NotebookEntryState> transformEvents(
    Stream<NotebookEntryEvent> events,
    Stream<NotebookEntryState> Function(NotebookEntryEvent event) next,
  ) {
    return super.transformEvents(
        events.debounceTime(const Duration(milliseconds: 500)), next);
  }

  @override
  Stream<NotebookEntryState> mapEventToState(NotebookEntryEvent event) async* {
    final currentState = state;
    logger.v('event: $event');

    ///Go to corresponding notebook page
    if (event is OnTapListTile) {
      yield DoingNothingState();
      yield GoToNoteEntryPage();
      return;
    }

    if (event is AddNewNotebook) {
      yield InputNotebookTitleState();
    }

    if (event is FetchNotebook && !_hasReachedMax(currentState)) {
      try {
        if (currentState is NotebookUninitialized) {
          final notebooks = await _fetchNotebooks(0, _fetchNumber);

          var countNotebooks = await _countNoteBooks();

          yield (notebooks.isEmpty || notebooks == null || notebooks.length <= countNotebooks)
              ? NotebookLoaded(notebooks: notebooks, hasReachedMax: true)
              : NotebookLoaded(notebooks: notebooks, hasReachedMax: false);

          return;
        }

        if (currentState is NotebookLoaded) {
          final notebooks =
              await _fetchNotebooks(currentState.notebooks.length, 20);
          yield (notebooks.isEmpty || notebooks == null)
              ? currentState.copyWith(hasReachedMax: true)
              : NotebookLoaded(
                  notebooks: currentState.notebooks + notebooks,
                  hasReachedMax: false,
                );
        } else {
          final notebooks = await _fetchNotebooks(0, 20);
          yield NotebookLoaded(notebooks: notebooks, hasReachedMax: false);
        }
      } catch (_) {
        logger.e(_);
        yield NotebookError();
      }
    }
  }

  bool _hasReachedMax(NotebookEntryState state) =>
      state is NotebookLoaded && state.hasReachedMax;

  Future<int> _countNoteBooks() async {
    //todo: modify users id
    return await NotebookDB.countNotebooksByUser(1);
  }

  Future<List<Notebook>> _fetchNotebooks(int startIndex, int limit) async {
    var res =
        await NotebookDB.fetchNotebooks(1, startIndex, limit).catchError((e) {
      logger.e(e);
      List<Notebook> nullNotes = [];
      return nullNotes;
    });

    return res;
  }
}


```

**Comment by masfranzhuo** [comment]
Hmm, you have initialized `NotebookEntryBloc` in BlocProvider, but why at onTap you called ` BlocProvider.of<EntryBloc>(context).add(AddNew());` from `EntryBloc` not `NotebookEntryBloc` ?

**Comment by duomoteng** [comment]
Sorry for the typo. (I just changed the name of the blocs) . It all should be NotebookEntryBloc. I have updated my post to make it clear.

**Comment by masfranzhuo** [comment]
Hmm, try this and see if it work in the `BlocProvider`
```
BlocProvider<NotebookEntryBloc>(
        create: (context) => NotebookEntryBloc()..add(FetchNotebook()),
        child: ...
```

**Comment by felangel** [comment]
Hi @duomoteng 👋 
Thanks for opening an issue!

This is because you're trying to access the bloc from the same `BuildContext` which was used to provide it.

To solve this you can either extract the `CupertinoPageScaffold` into a separate `StatelessWidget` or you can wrap it in a `Builder`.

```dart
class NotebookEntryPageProvider extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => NotebookEntryBloc()..add(FetchNotebook()),
      child: Scaffold(
        floatingActionButton: Center(
          child: FloatingActionButton(
            child: CupertinoTextField(),
            onPressed: () {},
          ),
        ),
        body: CupertinoPageScaffold(
          navigationBar: CupertinoNavigationBar(
            middle: Text("Title"),
            trailing: Builder(
              builder: (context) => GestureDetector(
                onTap: () {
                  BlocProvider.of<NotebookEntryBloc>(context).add(AddNew());
                },
                child: Icon(CupertinoIcons.add),
              ),
            ),
          ),
          child: EntryPage(),
        ),
      ),
    );
  }
}
```

Hope that helps! 👍
