### ISSUE TITLE
Bloc is closed before the test Case can complete

### ISSUE THREAD

**Issue by mzafer** [felangel/bloc#1299]
My test case fails with the below error. No idea what I am doing wrong. I have included the code to recreate the issue

```
ERROR: Unhandled error Bad state: Cannot add new events after calling close occurred in bloc Instance of 'MyLoginBloc'.
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
#1      Bloc.add (package:bloc/src/bloc.dart:158:24)
#2      MyLoginBloc.mapEventToState.<anonymous closure>
```

**Code to recreate the issue**

```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:bloc_test/bloc_test.dart';

class LoginRepo {
 String signIn(){
   return '100';
 }
}

abstract class MyLoginEvent extends Equatable {
  const MyLoginEvent();
  @override
  List<Object> get props => [];
}

class StartLogin extends MyLoginEvent {}
class CompleteLogin extends MyLoginEvent {}
class FailLogin extends MyLoginEvent {}

abstract class MyLoginState extends Equatable {
  const MyLoginState();

  @override
  List<Object> get props => [];
}
class InitialLoginState extends MyLoginState {}
class FailedLoginState extends MyLoginState {}
class SuccessLoginState extends MyLoginState {}

class MyLoginBloc extends Bloc<MyLoginEvent, MyLoginState> {
  final LoginRepo _loginRepo;
  StreamSubscription subscription;

    MyLoginBloc({@required LoginRepo loginRepo})
      : assert(loginRepo != null),
        _loginRepo = loginRepo;

  @override
  MyLoginState get initialState => InitialLoginState();

  @override
  Stream<MyLoginState> mapEventToState(
    MyLoginEvent event,
  ) async* {
    if( event is StartLogin){
      subscription = logMeIn().listen((evt) {
        add(evt);
      });
    } else if (event is CompleteLogin){
      yield SuccessLoginState();
    } else if (event is FailLogin) {
      yield FailedLoginState();
    }
  }

  Stream<MyLoginEvent> logMeIn() async* {
    StreamController<MyLoginEvent> eventStream = StreamController();
    try {
        String user = _loginRepo.signIn();
        if (user != null) {
          eventStream.add(CompleteLogin());
          eventStream.close();
        } else {
          eventStream.add(FailLogin());
          eventStream.close();
        }
      } catch (e) {
        eventStream.add(FailLogin());
          eventStream.close();
        print(e);
      }
      yield* eventStream.stream;
  }
}

void main() {
  group('Login Bloc ', () {
    MyLoginBloc myBloc;
    LoginRepo loginRepo;

    setUp(() {
     myBloc = new MyLoginBloc(loginRepo: new LoginRepo());
    
    });

     blocTest('emits [SuccessLoginState] after login', 
        build: () async {
          return myBloc;
        },
        act: (bloc) => bloc.add(StartLogin()),
        expect: [
            SuccessLoginState()
        ]
      );
  });
}


```

**Comment by QAQyzk** [comment]
I had same problem when I tries to do similar thing. Unable to solve the problem but find another way to test the function using the `test` function with `expectLater`.

```
test('emits [SuccessLoginState] after login', () {
      expectLater(
          myBloc, emitsInOrder([InitialLoginState(), SuccessLoginState()]));
      myBloc.add(StartLogin());
    });
```

**Comment by felangel** [comment]
Hi @mzafer 👋 
Thanks for opening an issue!

You can address this by adding a `wait` to your `blocTest` like so:

```dart
blocTest('emits [SuccessLoginState] after login',
  build: () async => MyLoginBloc(loginRepo: MockLoginRepo()),
  act: (bloc) async => bloc.add(StartLogin()),
  wait: Duration.zero,
  expect: [SuccessLoginState()],
);
```

This will force your bloc to wait one frame before closing the bloc. While this approach should work, I would highly recommend refactoring your bloc to avoid creating a new `StreamController` and instead do something like:

```dart
Stream<MyLoginEvent> logMeIn() async* {
  try {
    String user = _loginRepo.signIn();
    yield user != null ? SuccessLoginState() : FailureLoginState();
  } catch (_) {
    yield FailureLoginState()
  }
}
```

Then you don't need to unnecessarily add another event and require a `wait` in your `blocTest`.

Hope that helps 👍

**Comment by mzafer** [comment]
Thanks @QAQyzk  and @felangel. The wait worked. I simplified the use case here to recreate the issue, I have more complex scenarios requiring a need for the StreamController. Are there any concerns with using Streamcontroller, I understand that this is not a bloc question but any thoughts or pointer would help. Thanks
