### ISSUE TITLE
Tried to listen to an InheritedWidget in a life-cycle that will never be called again

### ISSUE THREAD

**Issue by Rahuvich** [felangel/bloc#1598]
Hello, I am coming from redux and I am learning how to use the BLoC pattern using `flutter_bloc: ^6.0.1`.

I am implementing an infinite list following [this tutorial](https://bloclibrary.dev/#/flutterinfinitelisttutorial) (with custom models) and I am getting the following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MainPage(dirty):
flutter: Tried to listen to an InheritedWidget in a life-cycle that will never be called again.
flutter: This error typically happens when calling Provider.of with `listen` to `true`,
flutter: in a situation where listening to the provider doesn't make sense, such as:
flutter: - initState of a StatefulWidget
flutter: - the "create" callback of a provider
flutter:
flutter: This is undesired because these life-cycles are called only once in the
flutter: lifetime of a widget. As such, while `listen` is `true`, the widget has
flutter: no mean to handle the update scenario.
flutter:
flutter: To fix, consider:
flutter: - passing `listen: false` to `Provider.of`
flutter: - use a life-cycle that handles updates (like didChangeDependencies)
flutter: - use a provider that handles updates (like ProxyProvider).
flutter:
flutter: The relevant error-causing widget was:
flutter:   MainPage file:///app/lib/ui/home_page/home_page.dart:84:21
```

The error is thrown when trying to paint MainPage widget, which is the following widget:

```
class MainPage extends StatelessWidget {
  final ScrollController scrollController;

  MainPage({this.scrollController});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AdsBloc, AdsState>(
      builder: (context, state) {
        if (state is AdsSuccess) {
          return _buildBody(context, state.category, state.paginatedAds.ads);
        }
        return _buildBody(context, state.category, []);
      },
    );
  }
}
```
**When this widget is removed from the tree, the app does not crash**. As I am new to BLoC, and also new to Provider, I can't find where is the bug. Any hint on the case will be highly appreciated.

**Comment by felangel** [comment]
Hi @Rahuvich 👋
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the problem you’re seeing? Thanks! 👍

**Comment by Rahuvich** [comment]
Hi @felangel, unfortunately I was trying BLoC on my personal project, so I can't share a link to a sample app for you to recreate the issue. 

I did my [personal project](https://github.com/Rahuvich/jumpets_app/tree/bloc) public in case you want to test it.  (There are a lot of files but as this issue seems to be an UI issue, you would only need to understand HomePage and MainPage widget.)

Stacktrace of the exception:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MainPage:
flutter: Tried to listen to an InheritedWidget in a life-cycle that will never be called again.
flutter: This error typically happens when calling Provider.of with `listen` to `true`,
flutter: in a situation where listening to the provider doesn't make sense, such as:
flutter: - initState of a StatefulWidget
flutter: - the "create" callback of a provider
flutter:
flutter: This is undesired because these life-cycles are called only once in the
flutter: lifetime of a widget. As such, while `listen` is `true`, the widget has
flutter: no mean to handle the update scenario.
flutter:
flutter: To fix, consider:
flutter: - passing `listen: false` to `Provider.of`
flutter: - use a life-cycle that handles updates (like didChangeDependencies)
flutter: - use a provider that handles updates (like ProxyProvider).
flutter:
flutter: The relevant error-causing widget was:
flutter:   MainPage file:///Users/raulmateobeneyto/Documentos/jumpets_app/lib/ui/home_page/home_page.dart:84:21
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _InheritedProviderScopeElement.dependOnInheritedElement.<anonymous closure> (package:provider/src/inherited_provider.dart:484:9)
flutter: #1      _InheritedProviderScopeElement.dependOnInheritedElement (package:provider/src/inherited_provider.dart:509:6)
flutter: #2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3885:14)
flutter: #3      MediaQuery.of (package:flutter/src/widgets/media_query.dart:814:38)
flutter: #4      MyApp.build.<anonymous closure> (package:jumpets_app/main.dart:23:39)
flutter: #5      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:612:35)
flutter: #6      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:475:33)
flutter: #7      Provider.of (package:provider/src/provider.dart:227:29)
flutter: #8      BlocProvider.of (package:flutter_bloc/src/bloc_provider.dart:110:23)
flutter: #9      BlocProviderExtension.bloc (package:flutter_bloc/src/bloc_provider.dart:148:53)
flutter: #10     _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:131:38)
flutter: #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
flutter: ...     Normal element mounting (39 frames)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
flutter: #53     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1164:36)
flutter: #54     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1149:20)
flutter: #55     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
flutter: #56     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1142:11)
flutter: #57     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356:23)
flutter: #58     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
flutter: #59     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
flutter: #60     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
flutter: #61     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345:5)
flutter: #62     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:429:5)
flutter: #63     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:199:12)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #65     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
flutter: #66     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:170:11)
flutter: #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #68     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #69     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
flutter: #70     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
flutter: #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #85     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #89     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #91     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #93     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
flutter: #94     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
flutter: #95     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
flutter: #96     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
flutter: #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #101    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #109    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #122    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
flutter: #123    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #126    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
flutter: #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #128    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #130    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #140    RenderView.performLayout (package:flutter/src/rendering/view.dart:170:13)
flutter: #141    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #142    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #143    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #144    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #145    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #146    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #147    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #148    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

Flutter doctor:
$ flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.4 19E287, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[!] Android Studio (not installed)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by sidy-refyne** [comment]
Just wanted to understand. why calling MediaQuery.of(context) inside creating the bloc is throwing the error. As I understand the context is BuildContext, which will have the access of the screen params. Calling it should work. rit?

**Comment by RollyPeres** [comment]
Hi @sidy-refyne 👋

You're getting that error simply because the inherited widget has no way of notifying the changes inside `create` since `create` is only called once, so basically it's an improper use of it.
