### ISSUE TITLE
Login tutorial error on logout

### ISSUE THREAD

**Issue by dariocast** [felangel/bloc#1904]
When I click on button to logout, following [login tutorial](https://bloclibrary.dev/#/flutterlogintutorial), I receive:
```
The following NoSuchMethodError was thrown building _InheritedProviderScope<AuthenticationBloc>(dirty, value: Instance of 'AuthenticationBloc', listening to value):
The getter 'id' was called on null.
Receiver: null
Tried calling: id

The relevant error-causing widget was: 
  BlocProvider<AuthenticationBloc> file:///D:/Development/FlutterProject/zama/lib/app.dart:27:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      HomePage.build.<anonymous closure>.<anonymous closure> (package:zama/home/view/home_page.dart:21:64)
#2      SelectContext.select.<anonymous closure> (package:provider/src/inherited_provider.dart:260:29)
#3      _InheritedProviderScopeElement.notifyDependent (package:provider/src/inherited_provider.dart:399:46)
#4      InheritedElement.notifyClients (package:flutter/src/widgets/framework.dart:5290:7)
```

I use flutter_bloc 6.1.0

**Comment by dariocast** [comment]
In flutter_bloc 6.0.0 the same tutorial works, I think there is something in the new select, is like it starts before the bloc listner above is advised of the new state.status

**Comment by dariocast** [comment]
I solved using a control statement:
```
final userId = context.select(
                  (AuthenticationBloc bloc) =>
                  bloc.state.user!=null ? bloc.state.user.id : null,
                );
```
instead of 
```
final userId = context.select(
                  (AuthenticationBloc bloc) => bloc.state.user.id,
                );
```

**Comment by felangel** [comment]
Hi @dariocast 👋 
Thanks for opening an issue!

This has been fixed in https://github.com/felangel/bloc/commit/1e3582f629452500ee8b45dc3871728ca105fa51 👍
