### ISSUE TITLE
Omitting `child` argument in `BlocListener` results in "Null check operator used on a null value"

### ISSUE THREAD

**Issue by comatory** [felangel/bloc#2600]
**Describe the bug**
When using `BlocListener` without `child` argument, application throws error 

> Null check operator used on a null value

**To Reproduce**
Create stateless widget, use `BlocListener` and do not provide `child` widget to component, leave it as `null`.

**Expected behavior**
Not getting error.

**Logs **
Flutter analyze does not show any problems. Stack trace of the error is something like this:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building BlocListener<OrderBloc, OrderState>(dirty, state:
_BlocListenerBaseState<OrderBloc, OrderState>#56655):
Null check operator used on a null value

The relevant error-causing widget was:
  BlocListener<OrderBloc, OrderState>
  file:///[..]/lib/widgets/home/views/component.dart:21:16

When the exception was thrown, this was the stack:
#0      _BlocListenerBaseState.buildWithChild (package:flutter_bloc/src/bloc_listener.dart:169:70)
#1      SingleChildState.build (package:nested/nested.dart:317:41)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#3      SingleChildStatefulElement.build (package:nested/nested.dart:339:18)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
#10     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (15 frames)
#25     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (15 frames)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#41     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
#43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#51     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#65     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
#66     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#93     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#102    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#105    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#107    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#110    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:456:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#112    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#113    _InheritedProviderScopeElement.update (package:provider/src/inherited_provider.dart:477:11)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#117    StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
#126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
#127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#130    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

**Comment by felangel** [comment]
Hi @comatory 👋 
Thanks for opening an issue! This is working as expected. The only time you should have a `null` child in `BlocListener` is when it is used within `MultiBlocListener`.

Hope that helps and closing for now 👍

**Comment by comatory** [comment]
Ok. I just did not notice this in documentation. Can you point me to relevant part please?

**Comment by felangel** [comment]
> Ok. I just did not notice this in documentation. Can you point me to relevant part please?

Did you take a look at https://bloclibrary.dev/#/flutterbloccoreconcepts?id=bloclistener? If you feel it's not clear enough feel free to open a pull request to improve the documentation 😄
