### ISSUE TITLE
docs: Readme example does not work

### ISSUE THREAD

**Issue by duzenko** [felangel/bloc#2706]
**Description**

The starting readme code does not work

```
Performing hot restart...
Syncing files to device AOSP on IA Emulator...
Restarted application in 780ms.

======== Exception caught by widgets library =======================================================
The following ProviderNotFoundException was thrown building _BodyBuilder:
Error: Could not find the correct Provider<CounterCubit> above this BlocBuilder<CounterCubit, int> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocBuilder<CounterCubit, int> is under your MultiProvider/Provider<CounterCubit>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

...

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter

The relevant error-causing widget was: 
  Scaffold file:///T:/qwe/lib/main.dart:31:12
When the exception was thrown, this was the stack: 
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:358:7)
#1      Provider.of (package:provider/src/provider.dart:295:30)
#2      ReadContext.read (package:provider/src/provider.dart:658:21)
#3      _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:130:36)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
...
====================================================================================================
```

Attached main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: CounterPage(),
    );
  }
}

class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);

  void increment() => emit(state + 1);
  void decrement() => emit(state - 1);
}

class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter')),
      body: BlocBuilder<CounterCubit, int>(
        builder: (context, count) => Center(child: Text('$count')),
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.add),
              onPressed: () => context.read<CounterCubit>().increment(),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.remove),
              onPressed: () => context.read<CounterCubit>().decrement(),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by duzenko** [comment]
Actually, I think this bug should be transferred to https://github.com/felangel/bloc/issues

**Comment by felangel** [comment]
Hi @duzenko 👋 
Thanks for opening an issue!

The snippet in the README is just to show how you would react to state changes in your UI. You can refer to the [complete example](https://pub.dev/packages/flutter_bloc/example) if you want to be able to run it locally. Sorry for the inconvenience and let me know if that helps 👍

**Comment by duzenko** [comment]
While your intention is good, it does not its purpose IMHO
It's misleading as it gives a false impression of 'ease of use'
It also does not do what it thinks it should
> Lets take a look at how to use BlocBuilder to hook up a CounterPage widget to a CounterCubit.
> At this point we have successfully separated our presentational layer from our business logic layer.

**Comment by felangel** [comment]
> While your intention is good, it does not serve its purpose IMHO
> It's misleading as it gives a false impression of 'ease of use'
> It also does not do what it thinks it should
> 
> > Lets take a look at how to use BlocBuilder to hook up a CounterPage widget to a CounterCubit.
> > At this point we have successfully separated our presentational layer from our business logic layer.

Sorry for the confusion, I’ll update the usage shortly to include the BlocProvider 👍
