### ISSUE TITLE
fix: Exception thrown inside of a bloc is ignored in integration tests

### ISSUE THREAD

**Issue by Giuspepe** [felangel/bloc#2819]
**Description**
When an exception is thrown inside of a bloc, it is ignored in integration tests and does not cause them to fail.
The bug occurs when running an integration test in which an exception is thrown inside of a bloc.

The last integration test inside this file is an example for such a case: https://github.com/Giuspepe/bloc/blob/master/packages/flutter_bloc/example/integration_test/app_test.dart

**Steps To Reproduce**
1. Clone the forked repository containing the minimum example: https://github.com/Giuspepe/bloc.git
2. Run the integration tests in `packages/flutter_bloc/example/integration_test`
I do this with the following configuration in Android Studio
![image](https://user-images.githubusercontent.com/39117631/135639280-35d6e022-1e21-426d-929d-cf5bcf7f2bf6.png)
3. The last test passes, but it should have actually failed. The logs contain this message: `The following BlocUnhandledErrorException was thrown running a test (but after the test had completed)`

**Expected Behavior**
An integration test should fail if an exception is thrown inside of a bloc.

**Screenshots**
The last test should have failed
![image](https://user-images.githubusercontent.com/39117631/135638936-0e3c3ceb-5f3c-401a-8236-bf0ad91f3de2.png)

Instead, it succeeds and the console output contains this message:
`The following BlocUnhandledErrorException was thrown running a test (but after the test had completed)`
(Note: to see this message, make sure you tap on `app_test.dart` in the console output in Android Studio, not on `Should fail but does not`)
![image](https://user-images.githubusercontent.com/39117631/135639385-d20cf310-2b72-41a4-b1e1-f0333508fe06.png)

**Additional Context**
This is the full message in the output:

```
SimpleBlocObserver.onError got the following error: Instance of 'ThrowExceptionInBloc'
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following BlocUnhandledErrorException was thrown running a test (but after the test had
completed):
Unhandled error Instance of 'ThrowExceptionInBloc' occurred in Instance of 'CounterBloc'.
#0      new CounterBloc.<anonymous closure> (package:example/main.dart:142:47)
#1      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:456:26)
#2      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:447:25)
#3      Bloc.on.<anonymous closure> (package:bloc/src/bloc.dart:464:9)
#4      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
#5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#6      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:26)
#7      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#8      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:14)
#9      _rootRunUnary (dart:async/zone.dart:1436:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#12     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#13     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:26)
#14     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#15     StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:14)
#16     _rootRunUnary (dart:async/zone.dart:1436:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#22     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#24     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:26)
#25     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#26     StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:126:14)
#27     _rootRunUnary (dart:async/zone.dart:1444:13)
#28     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#31     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#32     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#33     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#34     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#35     StackZoneSpecification._registerCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:116:48)
#36     _rootRun (dart:async/zone.dart:1420:47)
#37     _CustomZone.run (dart:async/zone.dart:1328:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#40     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#41     StackZoneSpecification._registerCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:116:48)
#42     _rootRun (dart:async/zone.dart:1428:13)
#43     _CustomZone.run (dart:async/zone.dart:1328:19)
#44     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#45     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

When the exception was thrown, this was the stack:
#0      BlocBase.onError.<anonymous closure> (package:bloc/src/bloc.dart:743:7)
#1      BlocBase.onError (package:bloc/src/bloc.dart:744:6)
#2      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:458:13)
#3      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:447:25)
#4      Bloc.on.<anonymous closure> (package:bloc/src/bloc.dart:464:9)
#13     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
(elided 43 frames from dart:async and package:stack_trace)
```

**Comment by marcossevilla** [comment]
hey @Giuspepe, I was checking at the example and had some doubts about it: why are you throwing an event on the event handler? that should exclusively emit bloc states.

Also, if you check on the integration test sample for [flutter_counter](https://github.com/felangel/bloc/blob/master/examples/flutter_counter/integration_test/app_test.dart) you can see there's an expect function to validate the UI output, but your test doesn't expect an exception to be thrown or some UI widget to be rendered.

Hope that helps and let me know if you have any other doubt. 👍

**Comment by Giuspepe** [comment]
Hey @marcossevilla thanks for your reply. 
I'm just throwing anything to make the minimal example as simple as possible.
In a real use case you could have an event handler which throws an error for any unexpected reason.
I would like integration tests to fail if there is an unhandled exception in an event handler.

**Comment by Giuspepe** [comment]
@marcossevilla thanks for your reply :) I'm not sure if we're talking about the same thing. My issue isn't that the tests should pass. They have to fail. But my issue is that I don't want to wait for the test to timeout until it fails, I want it to fail immediately when an exception is thrown inside a bloc. 
If you compare the behavior with the other test where the exception is thrown inside the `onPressed` of the TextButton, that test does fail immediately as soon as the exception is thrown. But the test where the exception is thrown inside of the bloc event handler, you have to wait for the timeout first until it fails.

Maybe the exception thrown in the event handler of the bloc is thrown to somewhere else. I tried wrapping that test with a try catch block, but the exception never shows up. If it did, the test would fail immediately when the exception is thrown instead of having to wait for the test timeout.

The exception even says that it was thrown after the test had completed which is not true `The following BlocUnhandledErrorException was thrown running a test (but after the test had completed)`. So there must be something wrong with the way that exceptions are thrown by blocs in integration tests.

**Comment by Giuspepe** [comment]
Oh I just found a way to fix it:

If you start the app in an integration test this way:
´´´dart
import 'package:my_package/main.dart' as app;

  testWidgets('Exceptions thrown in blocs are ignored', (WidgetTester tester) async {
      await tester.pumpWidget(app.App());
      ...
  });
´´´

You will get the behaviour I described that exceptions thrown inside of the bloc will not be able to be caught by the test and you have to wait until the test times out.

However, if you do it like this instead:

´´´dart
import 'package:my_package/main.dart' as app;

  testWidgets('Exceptions thrown in blocs actually arrive and the test fails as it should', (WidgetTester tester) async {
      app.main();
      ...
  });
´´´

Then it works and the test fails immediately, as it should. 

No idea why that solves it.
