### ISSUE TITLE
fix: Failed assertion: line 137 pos 7: '!_isCompleted' using stream

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2847]
**Description**

**Steps To Reproduce**

```
class SomeBloc extends Bloc<SomeEvent, SomeState> {
  final GetSomeUseCase _getSomeUseCase;
  SomeBloc(this._getSomeUseCase) : super(SomeInitial()) {
    on<GetSomeEvent>((event, emit) {
      emit(SomeLoading());
      _getSomeUseCase.call(event.params).listen((response) {

        if (response.isRight()) {
         
          emit(SomeSuccess(
              someEntity: response.getOrElse((l) => []).toList()));
        } else {
          emit(SomeFailure());
        }
      });
    });
  }
}
```

**Expected Behavior**
I am listening socket using stream, and response to come to the bloc takes 3-5 seconds. Having come response and emit ing it, bloc throws exception (```Failed assertion: line 137 pos 7: '!_isCompleted': ```)

Full log:
```
flutter: 'package:bloc/src/bloc.dart': Failed assertion: line 137 pos 7: '!_isCompleted': 


emit was called after an event handler completed normally.
This is usually due to an unawaited future in an event handler.
Please make sure to await all asynchronous operations with event handlers
and use emit.isDone after asynchronous operations before calling emit() to
ensure the event handler has not completed.

  **BAD**
  on<Event>((event, emit) {
    future.whenComplete(() => emit(...));
  });

  **GOOD**
  on<Event>((event, emit) async {
    await future.whenComplete(() => emit(...));
  });
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _Emitter.call (package:bloc/src/bloc.dart:137:7)
```
There is no futures are used inside **on** method

**Comment by stepanzalis** [comment]
Got similar error in this [issue](https://github.com/felangel/bloc/issues/2784). 😞

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

As @elianmortega mentioned, streams are asynchronous too and in your example you are leaking the stream subscription and emitting after the event handler has completed. You can support this use case with the new API like:

```dart
class SomeBloc extends Bloc<SomeEvent, SomeState> {
  final GetSomeUseCase _getSomeUseCase;
  SomeBloc(this._getSomeUseCase) : super(SomeInitial()) {
    on<GetSomeEvent>((event, emit) async {
      emit(SomeLoading());
      await emit.forEach(
        _getSomeUseCase.call(event.params),
        (response) => response.isRight() ? SomeSuccess(...) : SomeFailure(),
      );
    });
  }
}
```

Hope that helps 👍

**Comment by NayYairLinn933** [comment]
fgf

**Comment by aminarshadinia** [comment]
Hello guys
Thanks for your hard work.

I recently updated my bloc to 8.0.1 and facing the same issue that was mentioned in this topic.
so i tried these two approaches but none of them work for me
all i want is to set my states again after i call create...


This is my former approach that was completely ok.
```
saved: (e) async* {
        Either<NoteFailure, Unit> failureOrSuccess;

        yield state.copyWith(
          isSaving: true,
          saveFailureOrSuccessOption: none(),
        );

        if (state.note.failureOption.isNone()) {
          failureOrSuccess = state.isEditing
              ? await _noteRepository.update(state.note)
              : await _noteRepository.create(state.note);
        }
        yield state.copyWith(
          isSaving: false,
          showErrorMessages: true,
          saveFailureOrSuccessOption: optionOf(failureOrSuccess),
        );
      },
```

First approach
```
import 'package:bloc/bloc.dart';
import 'package:dartz/dartz.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:sample_app/domain/place/i_place_repository.dart';
import 'package:sample_app/domain/place/place.dart';
import 'package:sample_app/domain/place/place_failure.dart';
import 'package:sample_app/domain/place/value_objects.dart';

part 'place_form_event.dart';
part 'place_form_state.dart';
part 'place_form_bloc.freezed.dart';

@injectable
class PlaceFormBloc extends Bloc<PlaceFormEvent, PlaceFormState> {
  final IPlaceRepository _placeRepository;

  PlaceFormBloc.formBloc(this._placeRepository)
      : super(PlaceFormState.initial());

  PlaceFormBloc(this._placeRepository) : super(PlaceFormState.initial()) {
    on<PlaceFormEvent>((event, emit) {
      event.map(
        initialized: (e) async {
          emit(e.initialPlaceOption.fold(
            () => state,
            (initialPlace) => state.copyWith(
              place: initialPlace,
            ),
          ));
        },
        saved: (e) async {
          Either<PlaceFailure,Unit>? failureOrSuccess;
          emit(
            state.copyWith(
              isSaving: true,
              saveFailureOrSuccessOption: none(),
            ),
          );
          if (state.place.failureOption.isNone()) {
          failureOrSuccess = await _placeRepository.create(state.place);
          }
          emit(
            state.copyWith(
              isSaving: false,
              showErrorMessages: true,
              saveFailureOrSuccessOption: optionOf(failureOrSuccess),
            ),
          );
        },
      );
    });
  }
}
```

Second Approach
```
import 'package:bloc/bloc.dart';
import 'package:dartz/dartz.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:sample_app/domain/place/i_place_repository.dart';
import 'package:sample_app/domain/place/place.dart';
import 'package:sample_app/domain/place/place_failure.dart';
import 'package:sample_app/domain/place/value_objects.dart';

part 'place_form_event.dart';
part 'place_form_state.dart';
part 'place_form_bloc.freezed.dart';

@injectable
class PlaceFormBloc extends Bloc<PlaceFormEvent, PlaceFormState> {
  final IPlaceRepository _placeRepository;

  PlaceFormBloc.formBloc(this._placeRepository)
      : super(PlaceFormState.initial());

  PlaceFormBloc(this._placeRepository) : super(PlaceFormState.initial()) {
    on<PlaceFormEvent>((event, emit) {
      event.map(
        initialized: (e) async {
          emit(e.initialPlaceOption.fold(
            () => state,
            (initialPlace) => state.copyWith(
              place: initialPlace,
            ),
          ));
        },
        saved: (e) async {
          Either<PlaceFailure, Unit>? failureOrSuccess;
          emit(
            state.copyWith(
              isSaving: true,
              saveFailureOrSuccessOption: none(),
            ),
          );
          if (state.place.failureOption.isNone()) {
            await _placeRepository.create(state.place).whenComplete(
                  () => emit(
                    state.copyWith(
                      isSaving: false,
                      showErrorMessages: true,
                      saveFailureOrSuccessOption: optionOf(failureOrSuccess),
                    ),
                  ),
                );
          }
        },
      );
    });
  }
}

```

**Comment by ThatPham2000** [comment]
Hello @felangel 
When I change event.params (example: I re-login with another user and this bloc is wrapped MaterialApp).
How do I refresh the stream with other information?
