### ISSUE TITLE
fix: Cannot make freezed v. 1.0.0 and bloc v. 8.0.0 to work together (previously worked fine with mapEventToState)

### ISSUE THREAD

**Issue by scugn1zz0** [felangel/bloc#3014]
**Description**

**---> After the description there is a video of the issue I have recorded! <---**

The following is my classical implementation of bloc v. 7.0.0 and freezed:
```
import 'package:bloc/bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'counter_bloc.freezed.dart';

class CounterBloc extends Bloc<CounterEvent, CounterState> {
  /// 7.2.0 - WORKS
  CounterBloc() : super(CounterState.initial());
  @override
  Stream<CounterState> mapEventToState(CounterEvent event) async* {
    yield* event.map(
      initial: (e) async* {
        yield state.copyWith(value: 0);
      },
      increase: (e) async* {
        yield state.copyWith(value: state.value + 1);
      },
      decrease: (e) async* {
        yield state.copyWith(value: state.value - 1);
      },
    );
  }
}

@freezed
class CounterEvent with _$CounterEvent {
  const factory CounterEvent.initial() = _Initial;
  const factory CounterEvent.increase() = Increase;
  const factory CounterEvent.decrease() = Decrease;
}

@freezed
class CounterState with _$CounterState {
  const factory CounterState({
    required int value,
  }) = _CounterState;

  factory CounterState.initial() => const CounterState(value: 0);
}
```

I am trying to move this to the new API of 8.0.0 and so my bloc becomes:
```
class CounterBloc extends Bloc<CounterEvent, CounterState> {
  /// 8.0.0 - DOES NOT WORK
  CounterBloc() : super(CounterState.initial()) {
    on<CounterEvent>((event, emit) {
      on<Increase>((event, emit) {
        emit(CounterState(value: state.value + 1));
      });
      on<Decrease>((event, emit) {
        emit(CounterState(value: state.value - 1));
      });
    });
  }

(all the rest staying equal)
```
The issue with v. 8.0.0 version of the bloc is that it provokes an error:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unhandled error Bad state: on<Increase> was called multiple times. There should only be a single event handler per event type. occurred in Instance of 'CounterBloc'.
#0      Bloc.on.<anonymous closure> (package:bloc/src/bloc.dart:417:9)
#1      Bloc.on (package:bloc/src/bloc.dart:424:6)
#2      new CounterBloc.<anonymous closure> (package:counter_bloc_freezed/bloc/counter_bloc.dart:10:7)
#3      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:456:26)
#4      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:447:25)
#5      Bloc.on.<anonymous closure> (package:bloc/src/bloc.dart:464:9)
#6      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#8      _rootRunUnary (dart:async/zone.dart:1436:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244<…>
```

From the video recording you will see that also the first event for some reason IS NOT passed to the bloc, the first click on the decrement or increment button is lost! And from the second one onward every click there is the above mentioned error.

JFYI the way I pass event into my bloc from the UI is the following: 
```
child: FloatingActionButton(
                  onPressed: () {
                    context.read<CounterBloc>().add(const CounterEvent.decrease());
                  },
                  tooltip: 'Decrement',
                  child: const Icon(Icons.remove),
                )
```

**Video Recording**
https://share.getcloudapp.com/rRuWdZYG

**Expected Behavior**
I would expect a similar behavior between these two API, or at least not errors with v. 8.0.0

**Comment by jellynoone** [comment]
Hi, @scugn1zz0. Just at a quick glance you're assigning the listeners in a listener.

Meaning, the event is already handled by the first generic `on<CounterEvent>`. 

You define the **all** listeners in the body of the constructor (or at least not in another listener.) ie.:
```
CounterBloc() : super(CounterState.initial()) {
  on<Increase>((event, emit) {
    emit(CounterState(value: state.value + 1));
  });
  on<Decrease>((event, emit) {
    emit(CounterState(value: state.value - 1));
  });
}
```

**Comment by scugn1zz0** [comment]
Hey @jellynoone briliant!!! You are so right thanks!!
