### ISSUE TITLE
Flutter Bloc Test: ProviderNotFoundException was thrown building Builder

### ISSUE THREAD

**Issue by wisnuwiry** [felangel/bloc#3091]
**Description**
I am trying writing a widget test with bloc state management, but when adding widget BlocBuilder inside BlocProvider having an error like this.

**Steps To Reproduce**

**My Code**:

```dart

class MockLanguageBloc extends MockBloc<LanguageEvent, LanguageState>
    implements LanguageBloc {}

class FakeLanguageState extends Fake implements LanguageState {}

void main() {
  late MockLanguageBloc mockLanguageBloc;

  setUp(() async {
    mockLanguageBloc = MockLanguageBloc();
  });

  setUpAll(() {
    registerFallbackValue(FakeLanguageState());
  });

    testWidgets('Renders Settings Page', (tester) async {
      await tester.pumpWidget(
        MultiBlocProvider(
          providers: [
            BlocProvider(
              lazy: false,
              create: (_) => mockLanguageBloc,
            ),
          ],
          child: MaterialApp(
            home: Builder(
              builder: (context) {
                return BlocBuilder<LanguageBloc, LanguageState>(
                  builder: (context, state) {
                    return Text(state.language.toString());
                  },
                );
              },
            ),
          ),
        ),
      );
    });
}

```

**Error Log:**

```
The following ProviderNotFoundException was thrown building Builder:
Error: Could not find the correct Provider<LanguageBloc> above this BlocBuilder<LanguageBloc,
LanguageState> Widget

This happens because you used a 'BuildContext' that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your 'main.dart; and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a 'BuildContext' that is an ancestor of the provider you are trying to read.

  Make sure that BlocBuilder<LanguageBloc, LanguageState> is under your
MultiProvider/Provider<LanguageBloc>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  

  consider using `builder` like so:

  
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  
If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter

When the exception was thrown, this was the stack:
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:358:7)
#1      Provider.of (package:provider/src/provider.dart:295:30)
#2      ReadContext.read (package:provider/src/provider.dart:658:21)
#3      _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:129:36)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (175 frames)
#180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#181    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#182    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (385 frames)
#567    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#568    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#569    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#570    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:495:11)
#571    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#572    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#573    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#574    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:395:11)
...     Normal element mounting (7 frames)
#581    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#588    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#595    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#596    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#597    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#598    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#599    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:495:11)
#600    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#601    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#602    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#603    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:395:11)
...     Normal element mounting (7 frames)
#610    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#617    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#624    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#631    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#632    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#633    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#634    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#635    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1175:5)
#636    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1189:7)
#637    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#638    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#639    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1128:19)
#640    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#641    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#642    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#643    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#646    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#647    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#648    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#651    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#652    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
```

**Comment by felangel** [comment]
Hi @wisnuwiry 👋
Thanks for opening an issue!

You need to specify the type when you provide the bloc otherwise the inferred type is the Mock type so the lookup fails:

```dart
BlocProvider<LanguageBloc>(
  lazy: false,
  create: (_) => mockLanguageBloc,
),
```

Hope that helps 👍

**Comment by wisnuwiry** [comment]
Ok thanks @felangel , it worked
