### ISSUE TITLE
fix: New Flutter Bloc version doesn't work with Stream (emit)

### ISSUE THREAD

**Issue by imamabdulazis** [felangel/bloc#3239]
**Description**
I'm using this library for a few years and very helpful for state management, but after upgrading to a new version of flutter bloc with the new emit method, it's made doesn't work with [Stream](#) using [fold](#) method.

URL repository code : [LanguageBloc](https://github.com/imamabdulazis/FlutterCleanArchitecture/blob/main/lib/features/presentation/blocs/LanguageBloc.dart)

Error:
```shell
emit was called after an event handler completed normally.
This is usually due to an unawaited future in an event handler.
Please make sure to await all asynchronous operations with event handlers
and use emit.isDone after asynchronous operations before calling emit() to
ensure the event handler has not completed.

  **BAD**
  on<Event>((event, emit) {
    future.whenComplete(() => emit(...));
  });

  **GOOD**
  on<Event>((event, emit) async {
    await future.whenComplete(() => emit(...));
  });
flutter: ❎ STACKTRACE    :#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _Emitter.call (package:bloc/src/emitter.dart:114:7)
#3      new LanguageBloc.<anonymous closure>.<anonymous closure> (package:clean_architect/features/presentation/blocs/LanguageBloc.dart:70:15)
#4      _rootRunUnary (dart:async/zone.dart:1436:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#10     _StreamController._add (dart:async/stream_controller.dart:607:7)
#11     _StreamController.add (dart:async/stream_controller.dart:554:5)
#12     _OnErrorResumeStreamSink.onData (package<…>
```

**Code example**

```dart
LanguageBloc({
    required this.getPreferredLanguageUseCase,
    required this.updateLanguageUseCase,
  }) : super(LanguageLoaded(Locale(Languages.languages[1].code!))) {
    on<LanguageEvent>((event, emit) {
      if (event is ToggleLanguageEvent) {
        updateLanguageUseCase.execute(event.language!.code!).listen((event) {
          add(LoadPreferredLanguageEvent());
        });
      } else if (event is LoadPreferredLanguageEvent) {
        getPreferredLanguageUseCase.execute(NoParams()).listen((eventRes) {
         // this code doesn't work event move emit inside fold method
          emit(eventRes.fold(
            (_) => const LanguageError(
              'Ooops, something wring with translation',
            ),
            (values) => LanguageLoaded(Locale(values)),
          ));
        });
      }
    });
  }
```

previous version flutter bloc with this code, working properly with **yield**

```dart
LanguageBloc(
      {required this.getPreferredLanguage, required this.updateLanguage})
      : super(LanguageLoaded(Locale(Languages.languages[1].code!)));

  @override
  Stream<LanguageState> mapEventToState(LanguageEvent event) async* {
    if (event is ToggleLanguageEvent) {
      updateLanguage
          .execute(event.language!.code!)
          .listen((eventRes) => add(LoadPreferredLanguageEvent()));
    } else if (event is LoadPreferredLanguageEvent) {
      final Stream<Either<Failure, String>> response =
          getPreferredLanguage.execute(NoParams());

      await for (final eventRes in response) {
        yield* eventRes.fold((_) async* {
          yield LanguageError();
        }, (values) async* {
          yield LanguageLoaded(Locale(r));
        });
      }
    }
  }
```

and then I try to change with this schema of **emit**, but still doesn't work 

```dart
     eventRes.fold(
        (_) => emit(const LanguageError(
          'Ooops, something wring with translation',
        )),
        (values) =>emit( LanguageLoaded(Locale(values)),
      )
```

**Expected Behavior**

The result is returned localization code (en/id)

**Screenshots**
flutter bloc **cubit** for theme and **bloc** for localization

https://user-images.githubusercontent.com/39134128/154995639-b1b711ad-e3e3-43dd-8a21-2ce497ad47ec.mov

**Comment by felangel** [comment]
Hi @imamabdulazis 👋 
Thanks for opening an issue!

I recommend using `emit.forEach` when working with streams:

```dart
on<LanguageEvent>((event, emit) {
  if (event is ToggleLanguageEvent) {
    updateLanguageUseCase.execute(event.language!.code!).listen((event) {
      add(LoadPreferredLanguageEvent());
    });
  } else if (event is LoadPreferredLanguageEvent) {
    emit.forEach(
      getPreferredLanguageUseCase.execute(NoParams()),
      onData: (eventRes) {
        return eventRes.fold(
          (_) => const LanguageError('Ooops, something wring with translation'),
          (values) => LanguageLoaded(Locale(values)),
        );
      },
    )    
  }
});
```

Hope that helps 👍

**Comment by imamabdulazis** [comment]
@felangel Yeah, it helps me a lot. I was struggling for a few days with this issue.
Now work perfectly with `emit.forEach`
Thanks for sharing your workaround!

Best regards

**Comment by martynov-lab** [comment]
[felangel](https://github.com/felangel) How to implement a block if I need to listen to two streams? I'm building a video conferencing app. I listen to one stream when the participants join the room.  And I need to listen to the second one to update the data of each participant (Turned on video/audio or turned off).

```dart
class BlocVideoRoom extends Bloc<VideoRoomEvent, VideoRoomState> {
  final VideoRoomUseCase useCase;
  BlocVideoRoom({required this.useCase}) : super(VideoRoomInitial()) {
    on<VideoRoomJoinRoom>(_onVideoRoomJoinRoom);
  }
    void _onVideoRoomJoinRoom(
      VideoRoomJoinRoom event, Emitter<VideoRoomState> emit) async {
      //we send data to the server to create a room and add our media data to the room
      await useCase.joinRoom(event.room, event.user.name);
      //subscribe to the stream with data about the connected participants of the conference
      await emit.forEach(useCase.getParticipants(),
          onData: (Map<int, ParticipantEntity> participants) {
        return VideoRoomJoined(
          participants: participants,
        );
      });

    // await emit.forEach(useCase.getUpdatedMediaStatus(),
    //     onData: (Map<int, ParticipantEntity> updatedMediaStatus) {
    //   //add(VideoRoomJoinRoom(room: event.room));
    //   return VideoRoomUpdateMediaStatus(updatedMediaStatus: updatedMediaStatus);
    // });
  }
}

```
 I put "await" on the first stream, it won't come to the second steam.

**Comment by intellect4all** [comment]
I don't know if you still have this issue. But a possible workaround is to combine the streams from their sources with rxdart's CombineLatestStreams, then have bloc listen to the outputted combined stream. Read [this](https://pub.dev/documentation/rxdart/latest/rx/CombineLatestStream-class.html)

**Comment by fortinjoffrey** [comment]
What if I have an event triggered by a button that cancel the stream subscription ?
How would we do that using emit.forEach ?

**Comment by AhmedRazaKhan16** [comment]
forEach() method work fine but if i have multi lists in one state so they doesnt response any stream but first how to handle multiple streams in One State
Like:
 on<FetchMydata>(
      (event, emit) async {
      
       await emit.forEach<List<Company>>(
          FireBaseService.fetchCompanies(),
          onData: (companies) =>
              MyDataLoadedState(myCompanies: companies, myProducts: state.myProducts),
          onError: (error, stackTrace) {
            log("Error Fetching Companies: $error");
            return MyDataLoadedState();
          },
        );

     
  await emit.forEach<List<Product>>(
          FireBaseService.fetchProducts(),
          onData: (myproducts) =>
              MyDataLoadedState(myProducts: myproducts, myCompanies: state.myCompanies),
          onError: (error, stackTrace) {
            log("in Product Strema :$error $stackTrace");
            return ErrorMyDataState(
                message:
                    "Error Fatching Products Stream: $error  + $stackTrace");
          },
        );
     
      }
