### ISSUE TITLE
Error when calling undo() on a replay bloc

### ISSUE THREAD

**Issue by Haidar0096** [felangel/bloc#3327]
**Description**
I have this bloc:
```
class EditorBloc extends ReplayBloc<EditorEvent, EditorState> {

  EditorBloc(...) {

    on<Undo>((event, emit) async {
      emit(state.copyWith(...));
      await Future.delayed(Duration(seconds: 2));
      undo();
    }, transformer: ...);
```

I am getting an error on the line `undo()` above, this is the console output (it also includes logger's output to prove that first a state is emitted and then the error is coming from the library's `undo()` method:
```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onChange (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:182:13)
flutter: │ #1   BlocBase.emit (package:bloc/src/bloc_base.dart:98:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Editor bloc: state is changing 
flutter: │ 🐛 from:
flutter: │ 🐛 EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 to:
flutter: │ 🐛 EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: Some(Offset(100.0, 100.0)), selectedElementId: None)
flutter: │ 🐛 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_Undo' is not a subtype of type 'EditorEvent' of 'event'
#0      EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart)
#1      ReplayBlocMixin.emit.<anonymous closure> (package:replay_bloc/src/replay_bloc.dart:113:9)
#2      _Change.undo (package:replay_bloc/src/change_stack.dart:65:23)
#3      _ChangeStack.undo (package:replay_bloc/src/change_stack.dart:46:55)
#4      ReplayBlocMixin.undo (package:replay_bloc/src/replay_bloc.dart:128:31)
#5      new EditorBloc.<anonymous closure> (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:48:7)
<asynchronous suspension>
#6      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:211:13)
<asynchronous suspension>
```

here are the events: 
```
abstract class EditorEvent extends ReplayEvent {
  const EditorEvent();
}

class Undo extends EditorEvent {
  const Undo();
}
```

Even If I call it from the widget directly it does not help, this:
```
onPressed: () {
            // context.read<EditorBloc>().add(const Undo());
            context.read<EditorBloc>().undo();
          },
```

gives this log that contains the same error and very detailed list of events/states emitted before the error happened:

```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   new EditorBloc (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:34:13)
flutter: │ #1   $initGetIt.<anonymous closure> (package:photo_editor/dependency_injection/service_locator.config.dart:25:11)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 created editor bloc with state EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:174:13)
flutter: │ #1   Bloc.add (package:bloc/src/bloc.dart:83:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Editor Bloc: an event has arrived:
flutter: │ 💡 Instance of 'AddImage'
flutter: │ 💡 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onChange (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:180:13)
flutter: │ #1   BlocBase.emit (package:bloc/src/bloc_base.dart:98:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Editor bloc: state is changing 
flutter: │ 🐛 from:
flutter: │ 🐛 EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 to:
flutter: │ 🐛 EditorState(editor: Editor(elements: {Element(id: b124bfee-4a64-4975-96c4-d46074911de0, elementType: ElementType.image(file: File: '/home/haidar/Pictures/Screenshot from 2022-01-20 13-48-35.png'), rect: Rect.fromLTRB(0.0, 0.0, 250.0, 250.0), showOrder: 1)}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

======== Exception caught by gesture ===============================================================
The following _TypeError was thrown while handling a gesture:
type '_Undo' is not a subtype of type 'EditorEvent' of 'event'

When the exception was thrown, this was the stack: 
#0      EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart)
#1      ReplayBlocMixin.emit.<anonymous closure> (package:replay_bloc/src/replay_bloc.dart:113:9)
#2      _Change.undo (package:replay_bloc/src/change_stack.dart:65:23)
#3      _ChangeStack.undo (package:replay_bloc/src/change_stack.dart:46:55)
#4      ReplayBlocMixin.undo (package:replay_bloc/src/replay_bloc.dart:128:31)
#5      EditorAppBar._buildLowerRow.<anonymous closure> (package:photo_editor/ui/screens/editor_screen/widgets/editor_app_bar.dart:95:40)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#27     _invoke1 (dart:ui/hooks.dart:170:10)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#2271e
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(20.2, 53.8)
  finalLocalPosition: Offset(10.2, 15.0)
  button: 1
  sent tap down
====================================================================================================
```

I really don't understand the error, I am using the replay bloc as the documentation suggests on [pub.dev](https://pub.dev/packages/replay_bloc) .

**Comment by marcossevilla** [comment]
hi @Haidar0096 👋  can you share a minimal reproducible sample on [dartpad.dev](https://dartpad.dev)? You should be able to just call `context.read<EditorBloc>().undo()` but it seems like you have some transforming logic. Can you provide more context on what the event handler is supposed to do?

**Comment by Haidar0096** [comment]
@marcossevilla  I am not doing any logic in the `Undo` event handler, the `emit` above was just to prove that the bloc is emitting states correctly. Anyway, the project is big and I can't reproduce the error in a new demo project as I don't know what is the source of the error (I tried and I couldn't). I can share the original source code if you want and you can have a look at the bloc, but as I said, I am basically doing as mentioned above, if you want I will put the project [here](https://github.com/Haidar0096/Image-Editor-Desktop/tree/temp)  (make sure you are on branch temp) and you can specifically have a look at the bloc causing the error [here ](https://github.com/Haidar0096/Image-Editor-Desktop/tree/temp/lib/ui/screens/editor_screen/bloc) and the undo method is [here](https://github.com/Haidar0096/Image-Editor-Desktop/blob/46297cae152d0605d1da38c6366d5d93dc33dbad/lib/ui/screens/editor_screen/bloc/editor_bloc.dart#L97) (I commented that line but feel free to uncomment it and try pressing the undo button).

**Comment by marcossevilla** [comment]
oh yeah, that was confusing from my end! 😄  will try to put up a PR for that asap!

**Comment by Haidar0096** [comment]
> oh yeah, that was confusing from my end! smile will try to put up a PR for that asap!

I don't understand, you mean you found the source of the error? If yes then what is it so I can fix it? 😅

**Comment by marcossevilla** [comment]
@Haidar0096 the problem is that you can't undo/redo at that moment, I opened [this PR](https://github.com/Haidar0096/Image-Editor-Desktop/pull/1) that adds `canUndo`/`canRedo` checks before executing those actions, another check can be `shouldReplay` that for now checks if the initial values don't change but this can be adjusted because that state can be emitted later and that can cause problems but your issue should be resolved!

**Comment by marcossevilla** [comment]
undos have a ChangeStack, so if there's only one element in the stack, `canUndo` would be false. what are the steps you're following to reproduce the issue? I noticed the issue you reported was triggered by dragging and then undoing, but I'm not sure which steps to follow for this one. also, you can tweak the `shouldReplay` because that can be the reason why `canUndo` is false too, feel free to modify that as you see fit 👍

**Comment by Haidar0096** [comment]
@marcossevilla please have look at this log, this is run on your code from the PR, there is clearly more than 1 state emitted, but as you see at the end adding `Undo` event does nothing,  why are these states not saved on the `ChangeStack`? How can I in this case un-add an image? 

```
Performing hot restart...
Syncing files to device Linux...
Restarted application in 800ms.
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   new EditorBloc (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:62:13)
flutter: │ #1   $initGetIt.<anonymous closure> (package:photo_editor/dependency_injection/service_locator.config.dart:26:40)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 created editor bloc with state EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:46:13)
flutter: │ #1   Bloc.add (package:bloc/src/bloc.dart:83:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Editor Bloc: an event has arrived:
flutter: │ 💡 Instance of 'EditorImageAdded'
flutter: │ 💡 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onChange (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:52:13)
flutter: │ #1   BlocBase.emit (package:bloc/src/bloc_base.dart:98:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Editor bloc: state is changing 
flutter: │ 🐛 from:
flutter: │ 🐛 EditorState(editor: Editor(elements: {}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 to:
flutter: │ 🐛 EditorState(editor: Editor(elements: {Element(id: 89e76b7a-1422-4e2a-9209-1456723b5ac7, elementType: ElementType.image(path: /home/haidar/Pictures/Screenshot from 2022-01-20 13-48-35.png), rect: Rect.fromLTRB(0.0, 0.0, 250.0, 250.0), showOrder: 1)}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:46:13)
flutter: │ #1   Bloc.add (package:bloc/src/bloc.dart:83:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Editor Bloc: an event has arrived:
flutter: │ 💡 Instance of 'EditorImageAdded'
flutter: │ 💡 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onChange (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:52:13)
flutter: │ #1   BlocBase.emit (package:bloc/src/bloc_base.dart:98:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Editor bloc: state is changing 
flutter: │ 🐛 from:
flutter: │ 🐛 EditorState(editor: Editor(elements: {Element(id: 89e76b7a-1422-4e2a-9209-1456723b5ac7, elementType: ElementType.image(path: /home/haidar/Pictures/Screenshot from 2022-01-20 13-48-35.png), rect: Rect.fromLTRB(0.0, 0.0, 250.0, 250.0), showOrder: 1)}), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 to:
flutter: │ 🐛 EditorState(editor: Editor(elements: {
flutter: │ 🐛    Element(id: 89e76b7a-1422-4e2a-9209-1456723b5ac7, elementType: ElementType.image(path: /home/haidar/Pictures/Screenshot from 2022-01-20 13-48-35.png), rect: Rect.fromLTRB(0.0, 0.0, 250.0, 250.0), showOrder: 1),
flutter: │ 🐛    Element(id: 48a4073f-fc7a-4368-a207-cd598a213fe1, elementType: ElementType.image(path: /home/haidar/Pictures/download.jpeg), rect: Rect.fromLTRB(0.0, 0.0, 250.0, 250.0), showOrder: 2)
flutter: │ 🐛 }), draggedElementId: None, dragPosition: None, selectedElementId: None)
flutter: │ 🐛 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   EditorBloc.onEvent (package:photo_editor/ui/screens/editor_screen/bloc/editor_bloc.dart:46:13)
flutter: │ #1   Bloc.add (package:bloc/src/bloc.dart:83:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Editor Bloc: an event has arrived:
flutter: │ 💡 Instance of 'EditorUndoTapped'
flutter: │ 💡 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
