### ISSUE TITLE
fix: flutter_todos Example not working

### ISSUE THREAD

**Issue by mirozahorak** [felangel/bloc#3367]
**Description**
Tried updating all packages, does not help.
Simply running example in any target causes following error:

```
Error: Binding does not extend BindingBase
An instance of ServicesBinding was created but the BindingBase constructor was not called.
This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.
    at Object.throw_ [as throw] (http://localhost:53304/dart_sdk.js:5080:11)
at http://localhost:53304/packages/flutter/src/foundation/binding.dart.lib.js:98:23
at Function.checkInstance (http://localhost:53304/packages/flutter/src/foundation/binding.dart.lib.js:103:26)
at Function.get instance [as instance] (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:5825:35)
at OptionalMethodChannel.setMethodCallHandler (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:1592:74)
at restoration.RestorationManager.new.initChannels (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:865:50)
at new restoration.RestorationManager.new (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:1001:10)
at flutter_services_binding.FlutterServicesBinding.__.createRestorationManager (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:6044:14)
at flutter_services_binding.FlutterServicesBinding.__.initInstances (http://localhost:53304/packages/flutter/src/services/restoration.dart.lib.js:5868:40)
at flutter_services_binding.FlutterServicesBinding.__.flutter_services_binding._StandaloneBindingBase.new (http://localhost:53304/packages/flutter_services_binding/src/flutter_services_binding.dart.lib.js:105:10)
at flutter_services_binding.FlutterServicesBinding.__._StandaloneBindingBase_SchedulerBinding$36.new (http://localhost:53304/packages/flutter_services_binding/src/flutter_services_binding.dart.lib.js:137:62)
at flutter_services_binding.FlutterServicesBinding.__._StandaloneBindingBase_ServicesBinding$36.new (http://localhost:53304/packages/flutter_services_binding/src/flutter_services_binding.dart.lib.js:143:61)
at new flutter_services_binding.FlutterServicesBinding.__ (http://localhost:53304/packages/flutter_services_binding/src/flutter_services_binding.dart.lib.js:175:67)
at Function.ensureInitialized (http://localhost:53304/packages/flutter_services_binding/src/flutter_services_binding.dart.lib.js:153:87)
at main (http://localhost:53304/packages/flutter_todos/main_development.dart.lib.js:18:55)
    at main.next (<anonymous>)
    at runBody (http://localhost:53304/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:53304/dart_sdk.js:40691:7)
at main (http://localhost:53304/packages/flutter_todos/main_development.dart.lib.js:17:18)
at http://localhost:53304/web_entrypoint.dart.lib.js:38:33
    at Object._checkAndCall (http://localhost:53304/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:53304/dart_sdk.js:5284:17)
    at http://localhost:53304/dart_sdk.js:140291:18
    at Generator.next (<anonymous>)
    at http://localhost:53304/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:53304/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:53304/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:53304/dart_sdk.js:35999:49)
    at Function._propagateToListeners (http://localhost:53304/dart_sdk.js:36037:17)
    at _Future.new.[_completeWithValue] (http://localhost:53304/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53304/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:53304/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:53304/dart_sdk.js:40784:13)
    at http://localhost:53304/dart_sdk.js:36261:9
```

**Comment by felangel** [comment]
Hi @mirozahorak 👋 
Thanks for opening an issue!

Sorry about that, I must've missed it when doing the refactor to move away from `flutter_services_binding`. It should be fixed now but let me know if you run into issues 👍

**Comment by mirozahorak** [comment]
Hi @felangel that was quick response! Works like a charm now. 👍
Very helpful docs and examples, when trying to grasp idea behind Bloc to be able to move from provider for our next extremely complex project.
