### ISSUE TITLE
docs: Hydrated_bloc demo application not working on ubuntu 20.04

### ISSUE THREAD

**Issue by bovitt** [felangel/bloc#3397]
**Description**

Clearly describe what documentation you are looking to add or improve.

On my machine, the example described here: https://pub.dev/packages/hydrated_bloc/example is dysfunctional. The app will run but nothing shows up.

The error and stacktrace is this:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Binding does not extend BindingBase
An instance of ServicesBinding was created but the BindingBase constructor was not called.
This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.
#0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:353:9)
#1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:363:6)
#2      ServicesBinding.instance (package:flutter/src/services/binding.dart:48:54)
#3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:387:51)
#4      RestorationManager.initChannels (package:flutter/src/services/restoration.dart:169:32)
#5      new RestorationManager (package:flutter/src/services/restoration.dart:157:5)
#6      ServicesBinding.createRestorationManager (package:flutter/src/services/binding.dart:296:12)
#7      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:34:27)
#8      new _StandaloneBindingBase (package:flutter_services_binding/src/flutter_services_binding.dart:31:5)
#9      new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding (package:flutter_services_binding/src/flutter_services_binding.dart)
#10     new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding&ServicesBinding (package:flutter_services_binding/src/flutter_services_binding.dart)
#11     new FlutterServicesBinding._ (package:flutter_services_binding/src/flutter_services_binding.dart)
#12     new FlutterServicesBinding.ensureInitialized (package:flutter_services_binding/src/flutter_services_binding.dart:22:49)
#13     main (package:jellymonster/main.dart:10:26)
#14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
#15     _rootRun (dart:async/zone.dart:1426:13)
#16     _CustomZone.run (dart:async/zone.dart:1328:19)
#17     _runZoned (dart:async/zone.dart:1861:10)
#18     runZonedGuarded (dart:async/zone.dart:1849:12)
#19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by felangel** [comment]
Hi @bovitt 👋 
Thanks for opening an issue!

That example is out-dated because see https://pub.dev/packages/hydrated_bloc/versions/9.0.0-dev.2/example for the most up-to-date example and let me know if you're still experiencing issues. Thanks and sorry for the inconvenience!

**Comment by bovitt** [comment]
That works. Thank you
