### ISSUE TITLE
hydrated_bloc: Converting enum to an encodable object failed

### ISSUE THREAD

**Issue by alexursul** [felangel/bloc#3428]
hydrated_bloc fails to convert a state to json when there are enums like this:

```
import 'package:freezed_annotation/freezed_annotation.dart';

enum TaskTagStatus {
  @JsonValue(1)
  active(1),
  @JsonValue(2)
  deleted(2);

  const TaskTagStatus(this.value);

  final int value;
}
```

Is it a bug?
I've managed to make this work by adding custom toJson and fromJson converters while defining a freezed model which uses this enum, but I wonder if it can work out-of-the-box?

**Comment by felangel** [comment]
Hi @alexursul 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by alexursul** [comment]
Hi @felangel !
Please, have a look at this:

state.dart:
```
import 'package:freezed_annotation/freezed_annotation.dart';
part 'state.freezed.dart';
part 'state.g.dart';

@freezed
class SubmitFormState with _$SubmitFormState {
  @JsonSerializable(explicitToJson: true)
  const factory SubmitFormState({
    // some other props
    @Default(SubmitFormStatus.loading) status,
  }) = _SubmitFormState;

  factory SubmitFormState.fromJson(Map<String, dynamic> json) => _$SubmitFormStateFromJson(json);
}

enum SubmitFormStatus {
  @JsonValue(0)
  loading(0),
  @JsonValue(1)
  loaded(1),
  @JsonValue(2)
  submitted(2),
  @JsonValue(3)
  failed(3);

  const SubmitFormStatus(this.value);

  final int value;
}
```

main.dart:

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'state.dart';

void main() {
  runApp(const FormPage());
}

class FormPage extends StatelessWidget {
  const FormPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (BuildContext context) => SubmitFormBloc()..add(InitEvent()),
      child: Builder(builder: (context) => _buildPage(context)),
    );
  }

  Widget _buildPage(BuildContext context) {
    final bloc = BlocProvider.of<SubmitFormBloc>(context);

    return Container();
  }
}

class SubmitFormBloc extends HydratedBloc<FormEvent, SubmitFormState> {
  SubmitFormBloc() : super(const SubmitFormState()) {
    on<InitEvent>(_init);
  }

  void _init(InitEvent event, Emitter<SubmitFormState> emit) async {
    emit(state.copyWith(status: SubmitFormStatus.failed));
  }

  @override
  SubmitFormState? fromJson(Map<String, dynamic> json) => SubmitFormState.fromJson(json);

  @override
  Map<String, dynamic>? toJson(SubmitFormState state) => state.toJson();
}

abstract class FormEvent {}

class InitEvent extends FormEvent {}
```

pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  bloc:
  flutter_bloc:
  hydrated_bloc:

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1`
```

Exception:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'SubmitFormStatus'
#0      HydratedMixin._traverseWrite (package:hydrated_bloc/src/hydrated_bloc.dart:304:7)
#1      HydratedMixin._traverseComplexJson.<anonymous closure> (package:hydrated_bloc/src/hydrated_bloc.dart:344:26)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#3      HydratedMixin._traverseComplexJson (package:hydrated_bloc/src/hydrated_bloc.dart:341:14)
#4      HydratedMixin._traverseWrite (package:hydrated_bloc/src/hydrated_bloc.dart:286:42)
#5      HydratedMixin._toJson (package:hydrated_bloc/src/hydrated_bloc.dart:259:40)
#6      HydratedMixin.onChange (package:hydrated_bloc/src/hydrated_bloc.dart:241:25)
#7      BlocBase.emit (package:bloc/src/bloc_base.dart:98:7)
```

**Comment by alexursul** [comment]
Oh I've found my problem. Forgot to specify enum type. Sorry. 
```
@freezed
class SubmitFormState with _$SubmitFormState {
  @JsonSerializable(explicitToJson: true)
  const factory SubmitFormState({
    // some other props
    @Default(SubmitFormStatus.loading) /** --------> **/ SubmitFormStatus /** <------- **/ status,
  }) = _SubmitFormState;

  factory SubmitFormState.fromJson(Map<String, dynamic> json) => _$SubmitFormStateFromJson(json);
}
```
