### ISSUE TITLE
fix: [hydrated_bloc] hydrated_box.lock The process cannot access the file because another process has locked a portion of the file.

### ISSUE THREAD

**Issue by kateile** [felangel/bloc#3518]
**Description**
I can't run two apps simultaneously  on `windows` which both use `hydrated_bloc`. I think this is because I use the default storage `HydratedStorage` which under the hood utilize hive box named `hydrated_box` and maybe these two apps can't write and read simultaneously using the same box.

I think best way to solve this is to pass `custom hive box name` on `HydratedStorage.build(...)` with something like
```dart
  static Future<HydratedStorage> build({
    required Directory storageDirectory,
    HydratedCipher? encryptionCipher,
    String? boxName,
  })
```

**Steps To Reproduce**
Run two apps which both use HydratedStorage. some thing like
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: kIsWeb
        ? HydratedStorage.webStorageDirectory
        : await getTemporaryDirectory(),
  );

  runApp(const App());
}
```

**Expected Behavior**
User may be able to run many apps simultaneously made separately by lazy developers (who are lazy enough to implement custom storage).

**Screenshots**
no just blank screen

**Additional Context**
This is error log
> [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\TEMBOM~1\AppData\Local\Temp\hydrated_box.lock' (OS Error: The process cannot access the file because another process has locked a portion of the file.
> 
> , errno = 33)
> #0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1002:9)
> #1      _rootRunUnary (dart:async/zone.dart:1434:47)
> #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> <asynchronous suspension>
> #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81:5)
> <asynchronous suspension>
> #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
> <asynchronous suspension>
> #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:142:12)
> <asynchronous suspension>
> #6      HydratedStorage.build.<anonymous closure> (package:hydrated_bloc/src/hydrated_storage.dart:101:15)
> <asynchronous suspension>
> #7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
> <asynchronous suspension>
> #8      startApp (package:graph/utils/start_app.dart:20:26)
> <asynchronous suspension>
> #9      main (package:online/main.dart:8:3)
> <asynchronous suspension>
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\TEMBOM~1\AppData\Local\Temp\hydrated_box.lock' (OS Error: The process cannot access the file because another process has locked a portion of the file.
> 
> , errno = 33)
> #0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1002:9)
> #1      _rootRunUnary (dart:async/zone.dart:1434:47)
> #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> <asynchronous suspension>
> #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81:5)
> <asynchronous suspension>
> #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
> <asynchronous suspension>
> #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:142:12)
> <asynchronous suspension>
> #6      HydratedStorage.build.<anonymous closure> (package:hydrated_bloc/src/hydrated_storage.dart:101:15)
> <asynchronous suspension>
> #7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
> <asynchronous suspension>
> #8      startApp (package:graph/utils/start_app.dart:20:26)
> <asynchronous suspension>
> #9      main (package:online/main.dart:8:3)
> <asynchronous suspension>
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: Cannot delete file, path = 'C:\Users\TEMBOM~1\AppData\Local\Temp\hydrated_box.lock' (OS Error: The process cannot access the file because it is being used by another process.
> 
> , errno = 32)
> #0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
> #1      _rootRunUnary (dart:async/zone.dart:1434:47)
> #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> <asynchronous suspension>
> #3      StorageBackendVm._closeInternal (package:hive/src/backend/vm/storage_backend_vm.dart:215:5)
> <asynchronous suspension>
> #4      BoxBaseImpl.close (package:hive/src/box/box_base_impl.dart:173:5)
> <asynchronous suspension>

**Comment by andrewsheridan** [comment]
I'm also seeing this issue. Figured I would comment to "bump" the issue, since this thread hasn't seen any activity for over a year. Would love to see a resolution for this.

**Comment by ahmed-osama-saad** [comment]
I get this issue often in development, when restarting the app.

**Comment by felangel** [comment]
Closing this for now since there isn't enough information to reproduce and there have been a number of updates since this issue was filed. If anyone is still facing this using the latest stable version of the package, please file a new issue with a clear reproduction sample and steps, thanks! 🙏

**Comment by felangel** [comment]
> This issue is easily reprodusable by having two instances of a flutter app using hydrated bloc on Windows.

Are you still able to reproduce with hydrated_bloc v10?

**Comment by Rexios80** [comment]
> two instances

Hive does not support multiple application instances. That would very easily lead to box corruption.

**Comment by felangel** [comment]
Closing this as wont fix since as @Rexios80 pointed out this is a limitation of hive.

**Comment by suxoikorm** [comment]
I have a suspicion that this is happening because of OneDrive. All my users who encounter this error are storing their documents in OneDrive. It would be helpful if someone investigated this, and perhaps there should be a recommendation somewhere not to use getApplicationDocumentsDirectory on Windows.

**Comment by suxoikorm** [comment]
Also, it's important to note that this error can be caught in Flutter.
@felangel, could you please take a look when you have a moment?

**Comment by Anemony22** [comment]
Like @ahmed-osama-saad said, my team gets this issue whenever we hot reload the app. First hot reload creates the error, second hot reload works and clears it. Closing and reopening the app fully doesn't create the error. This happens every second hot reload.

**Comment by felangel** [comment]
> Like [@ahmed-osama-saad](https://github.com/ahmed-osama-saad) said, my team gets this issue whenever we hot reload the app. First hot reload creates the error, second hot reload works and clears it. Closing and reopening the app fully doesn't create the error. This happens every second hot reload.

Can you file a new issue with a minimal reproduction sample and clear steps to reproduce the issue? Thanks!
