### ISSUE TITLE
question: MultiBlocProvider doesn't work properly

### ISSUE THREAD

**Issue by engelin** [felangel/bloc#3584]
**Description**
1. flutter doctor -v
```shell
git:(main) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/arum/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/arum/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 12 (API 31) (emulator)
    • iPhone 14 (mobile)          • 7B7B5C90-D464-4F33-AD05-7B0DE795F57F • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

2. flutter bloc version
bloc: ^8.1.0
flutter_bloc: ^8.1.1

3. bottom_navigator_widget.dart
```dart
...
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
        providers: <BlocProvider>[
          BlocProvider(create: (_) => ABloc()),
          BlocProvider(create: (_) => BBloc()),
          BlocProvider(create: (_) => CBloc()),
          BlocProvider(create: (_) => DBloc()),
          BlocProvider(create: (_) => EBloc()),
          BlocProvider(create: (_) => FBloc()),
          BlocProvider(create: (_) => GBloc()),
        ],
        child: AutoTabsScaffold(
          routes: _routes,
          bottomNavigationBuilder: (_, tabsRouter) {
            return BottomNavigationBar(
              elevation: 10,
              type: BottomNavigationBarType.fixed,
              currentIndex: tabsRouter.activeIndex,
              onTap: tabsRouter.setActiveIndex,
              selectedFontSize: 12.0,
              items: _buildItems(),
            );
          },
        ),
      );
  }
...
```

Then, context couldn't find the right blocs as I've met this error:
- error log
```shell
======== Exception caught by widgets library =======================================================
The following ProviderNotFoundException was thrown building AView:
Error: Could not find the correct Provider<ABloc> above this BlocListener<ABloc, AState> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocListener<ToolBloc, ToolState> is under your MultiProvider/Provider<ToolBloc>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ``
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>().toString()),
    );
  }
  ``

  consider using `builder` like so:

  ``
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context, child) {
        // No longer throws
        return Text(context.watch<Example>().toString());
      }
    );
  }
  ``

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter

The relevant error-causing widget was: 
  CategoryToolView CategoryToolView:file:///Users/arum/workspace/code/arum-mobile-shops/lib/presentation/category/view/category_products_page.dart:30:11
When the exception was thrown, this was the stack: 
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343:7)
#1      Provider.of (package:provider/src/provider.dart:293:30)
#2      ReadContext.read (package:provider/src/provider.dart:649:21)
#3      _BlocListenerBaseState.initState (package:flutter_bloc/src/bloc_listener.dart:147:36)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#6      SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#14     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#17     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#18     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (13 frames)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#32     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
#34     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:227:11)
...     Normal element mounting (83 frames)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#118    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#119    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (282 frames)
#401    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#402    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#403    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#404    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#405    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#406    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#407    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#408    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#409    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#410    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#411    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#412    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#413    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#414    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#415    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#416    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#417    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#418    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#419    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#420    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#421    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#422    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#423    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#424    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#425    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#426    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#427    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#428    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#430    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#431    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#432    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#433    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#434    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#435    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#436    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#437    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#438    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#439    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#440    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#441    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#442    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#443    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#444    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#445    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#446    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#447    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#448    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#449    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#450    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#451    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#452    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#453    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#454    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#455    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#456    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#457    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#458    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#459    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#460    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#461    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#462    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#463    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#464    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#465    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#466    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#467    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#471    _invoke (dart:ui/hooks.dart:150:10)
#472    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#473    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

4. bottom_navigator_widget.dart - pass
But, if I just write like the below:
```dart
...
BlocProvider(
        create: (context) => ABloc(),
        child: BlocProvider(
          create: (context) => BBloc(),
          child: BlocProvider(
            create: (context) => CBloc(),
            child: BlocProvider(
              create: (context) => DBloc(),
              child: BlocProvider(
                create: (context) => EBloc(),
                child: BlocProvider(
                  create: (context) => FBloc(),
                  child: BlocProvider(
                    create: (context) => GBloc(),
...
```

It's working!

I was thinking it's very weird and wondering if I use MultiBlocProvider as a wrong way.
I didn't modify the code except for this provider.

**Comment by felangel** [comment]
@engelin I'm guessing you're using the parent context to access a bloc.

See the error message:

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocListener<ToolBloc, ToolState> is under your MultiProvider/Provider<ToolBloc>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```dart
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>().toString()),
    );
  }
  ```

  consider using `builder` like so:

  ```dart
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context, child) {
        // No longer throws
        return Text(context.watch<Example>().toString());
      }
    );
  }
  ```

**Comment by engelin** [comment]
@Luci3b @felangel 
Thank you for your answers.

I've just found out what the problem was. When I wrote the type of list, like the above description `MultiBlocProvider(providers: <BlocProvider>[])`, this error came out. But after removing this `<BlocProvider>`, it's working now!

Could you let me know the reason why I can't use this expression for multi bloc provider?

**Comment by felangel** [comment]
The reason is because the generic type cannot be inferred in that case. Internally, the list is typed as a `List<BlocProviderSingleChildWidget>` in order to allow `MultiBlocProvider` to infer the types of multiple `BlocProvider` instances correctly.
