### ISSUE TITLE
docs: example output in bloclibrary.dev#error-handling is not correctly

### ISSUE THREAD

**Issue by Nobler** [felangel/bloc#4012]
In [error-handling](https://bloclibrary.dev/#/coreconcepts?id=error-handling) section, the output is wrong:
```
Exception: increment error!, #0      CounterCubit.increment (file:///main.dart:21:56)
#1      main (file:///main.dart:41:7)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

CounterCubit Exception: increment error! #0      CounterCubit.increment (file:///main.dart:21:56)
#1      main (file:///main.dart:41:7)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Change { currentState: 0, nextState: 1 }
CounterCubit Change { currentState: 0, nextState: 1 }
```

The correct one should be:
```
Exception: increment error!, #0      CounterCubit.increment (package:dartdemo/dartdemo.dart:11:56)
#1      main (package:dartdemo/dartdemo.dart:45:7)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

CounterCubit Exception: increment error! #0      CounterCubit.increment (package:dartdemo/dartdemo.dart:11:56)
#1      main (package:dartdemo/dartdemo.dart:45:7)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

CounterCubit Change { currentState: 0, nextState: 1 }
Change { currentState: 0, nextState: 1 }
```

**Comment by felangel** [comment]
This has been addressed in https://github.com/felangel/bloc/commit/3f0ccb8e4c75e7d0b0559d4c6fb56bc738696bc1
