### ISSUE TITLE
fix: PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by callius** [felangel/bloc#4231]
**Description**
When using the bloc plugin for Intellij Idea Ultimate and right-clicking on a folder to open the menu, an IDE error occurs.

**Steps To Reproduce**
1. right-click on a folder to open the menu.

**Expected Behavior**
No error.

**Additional Context**
IDE version 2024.2.x.x
Plugin version 3.4.0

```console
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.bloc.intellij_generator_plugin.action.GenerateBlocAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.bloc.intellij_generator_plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by felangel** [comment]
This has been fixed in v4.0.2
