### ISSUE TITLE
Bloc unit test with StreamSubscription on the constructor cause "MissingPluginException"

### ISSUE THREAD

**Issue by abiliodasilva** [felangel/bloc#915]
Regards, dear @felangel
I have a doubt, when trying to implement the test of a particular Bloc that only allows me to know if the user's device has connectivity or not:

```dart
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:connectivity/connectivity.dart';

enum ConnectivityEvent {
  disable,
  enable,
}

class ConnectivityBloc extends Bloc<ConnectivityEvent, bool> {
  StreamSubscription _connectivitySubscription;

  ConnectivityBloc() {
    _connectivitySubscription = Connectivity().onConnectivityChanged.listen(
      (ConnectivityResult result) {
        if (result == ConnectivityResult.none) {
          add(ConnectivityEvent.disable);
        } else {
          add(ConnectivityEvent.enable);
        }
      },
    );
  }

  @override
  bool get initialState => false;

  @override
  Stream<bool> mapEventToState(ConnectivityEvent event) async* {
    switch (event) {
      case ConnectivityEvent.disable:
        yield false;
        break;
      case ConnectivityEvent.enable:
        yield true;
        break;
    }
  }

  @override
  Future<void> close() {
    _connectivitySubscription.cancel();
    return super.close();
  }
}
```

Using the following unit test:
```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:my_app/blocs/blocs.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('ConnectivityBloc', () {
    ConnectivityBloc connectivityBloc;

    setUp(() {
      connectivityBloc = ConnectivityBloc();
    });

    blocTest(
      'initial state is false',
      build: () => connectivityBloc,
      expect: [false],
    );

    blocTest(
      'state should be true on connection enable',
      build: () => connectivityBloc,
      act: (bloc) => bloc.add(ConnectivityEvent.enable),
      expect: [false, true],
    );
  });
}
```

The console prints out the next message everytime a blocTest is make it:
```log
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
plugins.flutter.io/connectivity_status:
MissingPluginException(No implementation found for method listen on channel
plugins.flutter.io/connectivity_status)

When the exception was thrown, this was the stack:
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
#14     new ConnectivityBloc (package:uba_app/blocs/connectivity/connectivity_bloc.dart:21:70)
#15     main.<anonymous closure>.<anonymous closure> (file:///C:/Apps/uba_app/test/blocs/connectivity_bloc_test.dart:11:26)
#16     Declarer._runSetUps.<anonymous closure> (package:test_api/src/backend/declarer.dart:294:51)
#28     Declarer._runSetUps (package:test_api/src/backend/declarer.dart:294:18)
#41     Declarer._runSetUps (package:test_api/src/backend/declarer.dart)
(elided 52 frames from package dart:async, package dart:async-patch, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:21 +2: All tests passed!
```

I think I understand the reason for this exception, after all the [connectivity package](https://pub.dev/packages/connectivity) is not available for native Dart and my OS (Windows) can't register it; only for Flutter [Android | iOS].

Is it possible to do the Bloc unit test without having to receive this exception messages?

My project info:
- flutter: 1.12.13+hotfix.7 stable
- bloc: 3.0.0
- flutter_bloc: 3.2.0
- connectivity: 0.4.8+1
- flutter_test: sdk: flutter
 - bloc_test: 3.1.0

**Comment by ResoDev** [comment]
Hello 👋
`Connectivity` depends on the native platform to access the network state and this is not possible inside a widget test.
Try mocking the instance of `Connectivity` with [mockito](https://github.com/dart-lang/mockito).

**Comment by abiliodasilva** [comment]
Thanks @ResoDev!
When applying your advice of trying to use `mockito` the exception stopped appearing, as a record, I leave here what I applied:

**connectivity_bloc.dart**
```dart
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:connectivity/connectivity.dart';
import 'package:meta/meta.dart';

enum ConnectivityEvent {
  disable,
  enable,
}

class ConnectivityBloc extends Bloc<ConnectivityEvent, bool> {
  final Stream<ConnectivityResult> connectivityStream;
  StreamSubscription _connectivitySubscription;

  ConnectivityBloc({
    @required this.connectivityStream,
  }) {
    _connectivitySubscription = connectivityStream.listen(
      (ConnectivityResult result) {
        if (result == ConnectivityResult.none) {
          add(ConnectivityEvent.disable);
        } else {
          add(ConnectivityEvent.enable);
        }
      },
    );
  }

  @override
  bool get initialState => false;

  @override
  Stream<bool> mapEventToState(ConnectivityEvent event) async* {
    switch (event) {
      case ConnectivityEvent.disable:
        yield false;
        break;
      case ConnectivityEvent.enable:
        yield true;
        break;
    }
  }

  @override
  Future<void> close() {
    _connectivitySubscription.cancel();
    return super.close();
  }
}
```

**connectivity_bloc_test.dart**
```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:connectivity/connectivity.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:my_app/blocs/blocs.dart';

class MockConnectivity extends Mock implements Connectivity {}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  
  group('ConnectivityBloc', () {
    Connectivity connectivity;
    Stream<ConnectivityResult> connectivityStream;
    ConnectivityBloc connectivityBloc;

    setUp(() {
      connectivity = MockConnectivity();
      when(connectivity.onConnectivityChanged).thenAnswer((_) {
        return Stream.value(ConnectivityResult.none);
      });

      connectivityStream = connectivity.onConnectivityChanged;
      connectivityBloc = ConnectivityBloc(connectivityStream: connectivityStream);
    });

    blocTest(
      'initial state is false',
      build: () => connectivityBloc,
      expect: [false],
    );

    blocTest(
      'state should be true on connection enable',
      build: () => connectivityBloc,
      act: (bloc) => bloc.add(ConnectivityEvent.enable),
      expect: [false, true],
    );
  });
}
```

**Console output**
```log
$ flutter test
00:06 +2: All tests passed!
```

**Comment by linxkaa** [comment]
Hi, 

I have a questions regarding accessing the private value in class, its always give me this error
`LateInitializationError: Field '_tweetSubscription@22285991' has not been initialized.`

because in my `TweetBloc` file, I initialize StreamSubscription which is `late` and have its value when `TweetEvent.initial(userId)` event hit. But since its mock, Its giving me those error. While everything is working fine when i run it in the emulator ( not in test mode )

This was my TweetBloc.

```dart
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:twitter/infrastructure/dtos/user_all_tweets_model.dart';
import 'package:twitter/infrastructure/repositories/tweet_repositories.dart';

part 'tweets_event.dart';
part 'tweets_state.dart';
part 'tweets_bloc.freezed.dart';

@injectable
class TweetsBloc extends Bloc<TweetsEvent, TweetsState> {
  final TweeetRepositories _repositories;
  late StreamSubscription<UserAllTweetsModel> _tweetSubscription;
  TweetsBloc(this._repositories) : super(TweetsState.initial());

  @override
  Stream<TweetsState> mapEventToState(
    TweetsEvent event,
  ) async* {
    yield* event.map(
      initial: (e) async* {
        yield state.unmodified.copyWith(isLoading: true);
        await Future.delayed(Duration(seconds: 1));
        _tweetSubscription = this._repositories.getUserTweets(userId: e.userId).listen((_listener));
      },
      newTweetsStreamed: (e) async* {
        yield state.unmodified.copyWith(mod: e.mod);
      },
    );
  }

  _listener(event) {
    add(TweetsEvent.newTweetsStreamed(event));
  }

  @override
  Future<void> close() {
    _tweetSubscription.cancel();
    return super.close();
  }
}
```

This was my tweets_bloc_test
```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:twitter/application/tweets_bloc/tweets_bloc.dart';
import 'package:twitter/infrastructure/dtos/user_all_tweets_model.dart';
import 'package:twitter/infrastructure/repositories/tweet_repositories.dart';
import 'dart:async';

import '../../domain/core/test_constant.dart';
import 'tweets_bloc_test.mocks.dart';

@GenerateMocks([TweeetRepositories])
void main() {
  group("Tweets Bloc Event -> initial ", () {
    TestWidgetsFlutterBinding.ensureInitialized();

    UserAllTweetsModel modelConstant = UserAllTweetsModel(
      tweets: [
        TweetModel(
          content: "test",
          userId: "1234",
          timestamp: TestConstant.dateTime,
          uniqueId: "uniqueId112233",
        )
      ],
      name: "test",
      email: "test@gmail.com",
      profilePicture: "www.google.com",
    );
    late MockTweeetRepositories _tweetRepositories;
    late TweetsBloc _tweetsBloc;
    setUp(() {
      _tweetRepositories = MockTweeetRepositories();

      _tweetsBloc = TweetsBloc(_tweetRepositories);
    });

    // blocTest<TweetsBloc, TweetsState>(
    //   'emits List<TweetModel> when TweetsEvent.initial("1234") is added.',
    //   build: () {
    //     when(_tweetRepositories.getUserTweets(userId: "1234")).thenAnswer(
    //       (_) => Stream.value(modelConstant),
    //     );
    //     return _tweetsBloc;
    //   },
    //   act: (bloc) => bloc.add(TweetsEvent.initial("1234")),
    //   expect: () => <TweetsState>[
    //     TweetsState.initial().copyWith(isLoading: true),
    //     TweetsState.initial().copyWith(
    //       mod: modelConstant,
    //     ),
    //   ],
    // );

    blocTest<TweetsBloc, TweetsState>(
      'emits UserAllTweetModel when TweetsEvent.newTweetsStreamed(modelConstante) is added.',
      build: () {
        return _tweetsBloc;
      },
      act: (bloc) => bloc.add(TweetsEvent.newTweetsStreamed(modelConstant)),
      expect: () => <TweetsState>[
        TweetsState.initial().copyWith(
          mod: modelConstant,
        ),
      ],
    );
  });
}
```

Thank you in advanced.
